# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('movement_type', models.CharField(choices=[('TRASLADO', 'Traslado entre agencias/áreas'), ('PRESTAMO', 'Préstamo temporal'), ('DEVOLUCION', 'Devolución de préstamo'), ('REASIGNACION', 'Reasignación de custodio'), ('INGRESO', 'Ingreso inicial'), ('BAJA', 'Baja / Retiro')], max_length=15, verbose_name='Tipo de movimiento')),
                ('movement_date', models.DateField(verbose_name='Fecha del movimiento')),
                ('reason', models.TextField(verbose_name='Motivo del movimiento')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('document_ref', models.CharField(blank=True, max_length=50, verbose_name='N° documento / acta')),
                ('is_cascade', models.BooleanField(default=False, verbose_name='Generado por arrastre')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Movimiento de activo',
                'verbose_name_plural': 'Movimientos de activos',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
