# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movements', '0001_initial'),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_movements', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='dest_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='locations.agency', verbose_name='Agencia destino'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='dest_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='locations.area', verbose_name='Área destino'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='dest_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to=settings.AUTH_USER_MODEL, verbose_name='Custodio destino'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='dest_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='locations.department', verbose_name='Depto. destino'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='origin_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='locations.agency', verbose_name='Agencia origen'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='origin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='locations.area', verbose_name='Área origen'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='origin_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to=settings.AUTH_USER_MODEL, verbose_name='Custodio origen'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='origin_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='locations.department', verbose_name='Depto. origen'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='parent_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_movements', to='movements.assetmovement', verbose_name='Movimiento padre (arrastre)'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='assetmovement',
            index=models.Index(fields=['asset', 'movement_date'], name='idx_mov_asset_date'),
        ),
        migrations.AddIndex(
            model_name='assetmovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='idx_mov_type_date'),
        ),
        migrations.AddIndex(
            model_name='assetmovement',
            index=models.Index(fields=['dest_agency'], name='idx_mov_dest_agency'),
        ),
    ]
