# Generated by Django 4.2.13 on 2026-04-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0002_assetmodel_type_nullable_remove_specs'),
        ('movements', '0003_migrate_custodians_to_custodian_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='has_delivery_act',
            field=models.BooleanField(default=False, verbose_name='¿Entregado con acta?'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='dest_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='custodians.custodian', verbose_name='Custodio destino'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='origin_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='custodians.custodian', verbose_name='Custodio origen'),
        ),
    ]
