# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Referencia')),
                ('entry_date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('entry_data', models.JSONField(verbose_name='Datos del asiento')),
                ('entry_type', models.CharField(choices=[('DEPRECIATION', 'Depreciación'), ('SALE', 'Venta'), ('ADJUSTMENT', 'Ajuste')], max_length=30, verbose_name='Tipo')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Contabilizado')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nombre del comprador')),
                ('buyer_id', models.CharField(max_length=13, verbose_name='CI/RUC comprador')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='N° factura de venta')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio de venta')),
                ('book_value_at_sale', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor en libros al momento de venta')),
                ('accumulated_dep', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Depreciación acumulada al vender')),
                ('sale_result', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Resultado (ganancia/pérdida)')),
                ('result_type', models.CharField(choices=[('GANANCIA', 'Ganancia en venta'), ('PERDIDA', 'Pérdida en venta')], max_length=10, verbose_name='Tipo de resultado')),
                ('seps_account', models.CharField(max_length=10, verbose_name='Cuenta SEPS (4103/5103)')),
                ('journal_entry_generated', models.BooleanField(default=False, verbose_name='Asiento generado')),
                ('journal_entry_data', models.JSONField(blank=True, null=True, verbose_name='Datos del asiento')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Venta de activo',
                'verbose_name_plural': 'Ventas de activos',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('period_date', models.DateField(verbose_name='Fecha del período')),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor inicial período')),
                ('monthly_depreciation', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Depreciación mensual')),
                ('accumulated', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Depreciación acumulada')),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor en libros al cierre')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('journal_entry_ref', models.CharField(blank=True, max_length=50, verbose_name='Ref. asiento contable')),
            ],
            options={
                'verbose_name': 'Cuota de depreciación',
                'verbose_name_plural': 'Cronograma de depreciación',
                'ordering': ['asset', 'period_year', 'period_month'],
            },
        ),
    ]
