# Generated by Django 4.2.13 on 2026-04-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('custodians', '0002_assetmodel_type_nullable_remove_specs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodian',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Custodio', 'verbose_name_plural': 'Custodios'},
        ),
        migrations.AddField(
            model_name='custodian',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodians', to='locations.agency', verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='id_number',
            field=models.CharField(blank=True, help_text='Cédula de identidad ecuatoriana (opcional).', max_length=13, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivación lógica. El registro nunca se elimina para preservar la trazabilidad histórica.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Cargo'),
        ),
        migrations.AddIndex(
            model_name='custodian',
            index=models.Index(fields=['agency'], name='idx_custodian_agency'),
        ),
    ]
