# Generated by Django 4.2.13 on 2026-04-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0003_add_agency_optional_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
