# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('FACTURA', 'Factura de compra'), ('CONTRATO', 'Contrato'), ('MANUAL', 'Manual / Guía'), ('GARANTIA', 'Certificado de garantía'), ('FOTO', 'Fotografía'), ('ACTA_ENTREGA', 'Acta de entrega'), ('SEGURO', 'Póliza de seguro'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de activo',
                'verbose_name_plural': 'Documentos de activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
