# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del usuario')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rol del usuario')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('VIEW', 'Consulta'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('MFA_ENABLED', 'MFA activado'), ('MFA_DISABLED', 'MFA desactivado'), ('DEPRECIATION', 'Depreciación calculada'), ('ASSET_SALE', 'Venta de activo'), ('ASSET_TRANSFER', 'Traslado de activo'), ('ASSET_DEACTIVATION', 'Baja de activo'), ('ASSET_ACTIVATION', 'Ingreso de activo'), ('MAINTENANCE', 'Mantenimiento registrado'), ('REPORT_GENERATED', 'Reporte generado'), ('DOCUMENT_GENERATED', 'Documento generado'), ('INVOICE_SCANNED', 'Factura escaneada'), ('COMPLIANCE_CHECK', 'Verificación de cumplimiento')], max_length=30, verbose_name='Acción')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo afectado')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Módulo')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('object_code', models.CharField(blank=True, max_length=100, verbose_name='Código del objeto')),
                ('object_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del objeto')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='Campos modificados')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ['-action_date'],
            },
        ),
    ]
