# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('alert_type', models.CharField(choices=[('GARANTIA_VENCE', 'Garantía próxima a vencer'), ('GARANTIA_VENCIDA', 'Garantía vencida'), ('MANTENIMIENTO_DUE', 'Mantenimiento programado próximo'), ('MANTENIMIENTO_VENC', 'Mantenimiento vencido'), ('DEPRECIACION_TOTAL', 'Activo totalmente depreciado'), ('LICENCIA_VENCE', 'Licencia de software próxima a vencer'), ('LICENCIA_VENCIDA', 'Licencia de software vencida'), ('ACTIVO_CRITICO', 'Alerta de activo crítico TI'), ('SEGURIDAD', 'Alerta de seguridad'), ('BAJA_PENDIENTE', 'Baja pendiente de autorización'), ('TRASLADO', 'Notificación de traslado'), ('CUSTOM', 'Alerta personalizada')], max_length=25, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja'), ('INFO', 'Informativa')], default='MEDIA', max_length=10, verbose_name='Severidad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('target_roles', models.JSONField(default=list, verbose_name='Roles destinatarios')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Nota de resolución')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Auto-generada')),
                ('notified_ws', models.BooleanField(default=False, verbose_name='Notificada por WebSocket')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
