# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('asset_code', models.CharField(max_length=30, unique=True, verbose_name='Código de activo')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de serie')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre / Descripción')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('category', models.CharField(choices=[('COMPUTO', 'Equipo de cómputo'), ('VEHICULO', 'Vehículo'), ('MAQUINARIA', 'Maquinaria y equipo'), ('MUEBLE', 'Mueble y ensere'), ('INMUEBLE', 'Inmueble / Edificio'), ('TELECOMUNICACION', 'Telecomunicaciones'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo / Baja'), ('MANTENIMIENTO', 'En mantenimiento'), ('VENDIDO', 'Vendido'), ('PRESTADO', 'En préstamo'), ('ROBADO', 'Robado / Siniestro')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('component_type', models.CharField(blank=True, choices=[('MONITOR', 'Monitor'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('PARLANTE', 'Parlante / Bocina'), ('ANTENA_WIFI', 'Antena WiFi'), ('UPS', 'UPS / Regulador'), ('DOCKING', 'Docking Station'), ('PATCH_PANEL', 'Patch Panel'), ('KVM', 'Switch KVM'), ('RACK', 'Rack / Gabinete'), ('SWITCH', 'Switch de red'), ('DISCO', 'Disco duro adicional'), ('MEMORIA', 'Módulo de memoria'), ('IMPRESORA', 'Impresora'), ('CAMARA', 'Cámara / Escáner'), ('OTRO', 'Otro componente')], max_length=20, null=True, verbose_name='Tipo de componente')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor de compra')),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor residual')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor en libros')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Depreciación acumulada')),
                ('purchase_date', models.DateField(verbose_name='Fecha de compra')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('deactivation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento garantía')),
                ('useful_life_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vida útil (años)')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tasa depreciación %')),
                ('is_fully_depreciated', models.BooleanField(default=False, verbose_name='Totalmente depreciado')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='N° de factura')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='Imagen factura')),
                ('seps_account_code', models.CharField(blank=True, max_length=20, verbose_name='Cuenta SEPS (18xx)')),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en inventario')),
                ('is_critical_it', models.BooleanField(default=False, verbose_name='Activo crítico TI')),
                ('requires_maintenance', models.BooleanField(default=False, verbose_name='Requiere mantenimiento')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
