# Generated by Django 4.2.13 on 2026-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_code_prefix_to_assettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='is_it_managed',
            field=models.BooleanField(default=False, help_text='Aparece en el módulo TI (hostname, IP, SO, etc.)', verbose_name='Gestionado por TI'),
        ),
    ]
