# Generated by Django 4.2.13 on 2026-04-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0002_assetmodel_type_nullable_remove_specs'),
        ('assets', '0007_migrate_custodian_to_custodian_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='specs',
        ),
        migrations.AlterField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='custodians.custodian', verbose_name='Custodio'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='assets.assettype', verbose_name='Tipo'),
        ),
    ]
