# Generated by Django 4.2.13 on 2026-04-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetmodel_type_nullable_remove_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='component_type_link',
            field=models.CharField(blank=True, choices=[('MONITOR', 'Monitor'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('PARLANTE', 'Parlante / Bocina'), ('ANTENA_WIFI', 'Antena WiFi'), ('UPS', 'UPS / Regulador'), ('DOCKING', 'Docking Station'), ('PATCH_PANEL', 'Patch Panel'), ('KVM', 'Switch KVM'), ('RACK', 'Rack / Gabinete'), ('SWITCH', 'Switch de red'), ('DISCO', 'Disco duro adicional'), ('MEMORIA', 'Módulo de memoria'), ('IMPRESORA', 'Impresora'), ('CAMARA', 'Cámara / Escáner'), ('OTRO', 'Otro componente')], help_text='Vincula este AssetType con un ComponentType para generación automática de código al crear componentes', max_length=20, null=True, verbose_name='Tipo de componente vinculado'),
        ),
    ]
