# Generated by Django 4.2.13 on 2026-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assettype_component_type_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='seps_account_code',
        ),
        migrations.AddField(
            model_name='asset',
            name='account_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuenta contable'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='category',
            field=models.CharField(choices=[('COMPUTO', 'Equipo de cómputo'), ('VEHICULO', 'Vehículo'), ('MAQUINARIA', 'Maquinaria y equipo'), ('MUEBLE', 'Mueble y ensere'), ('INMUEBLE', 'Inmueble / Edificio'), ('TELECOMUNICACION', 'Telecomunicaciones'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría'),
        ),
    ]
