# Generated by Django 4.2.13 on 2026-04-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_rename_seps_to_account_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='account_code',
        ),
    ]
