# Generated by Django 4.2.13 on 2026-04-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0011_remove_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, choices=[('COMPUTO', 'Equipo de cómputo'), ('VEHICULO', 'Vehículo'), ('MAQUINARIA', 'Maquinaria y equipo'), ('MUEBLE', 'Mueble y ensere'), ('INMUEBLE', 'Inmueble / Edificio'), ('TELECOMUNICACION', 'Telecomunicaciones'), ('OTRO', 'Otro')], help_text='Categoría de activo con la que se asocia por defecto (opcional).', max_length=20, null=True, verbose_name='Categoría sugerida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.accountcode', verbose_name='Cuenta contable'),
        ),
        migrations.AddIndex(
            model_name='accountcode',
            index=models.Index(fields=['code'], name='idx_account_code'),
        ),
    ]
