# Generated by Django 4.2.13 on 2026-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_add_account_code_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje anual de depreciación (ej: 33.33).', max_digits=6, null=True, verbose_name='Tasa de depreciación (%)'),
        ),
        migrations.AddField(
            model_name='accountcode',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Años de vida útil para depreciar activos de esta cuenta.', null=True, verbose_name='Vida útil (años)'),
        ),
    ]
