# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAssetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname / Nombre de equipo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC')),
                ('os_name', models.CharField(blank=True, max_length=100, verbose_name='Sistema operativo')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='Versión SO')),
                ('processor', models.CharField(blank=True, max_length=150, verbose_name='Procesador')),
                ('ram_gb', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Almacenamiento (GB)')),
                ('risk_level', models.CharField(choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='BAJO', max_length=10, verbose_name='Nivel de riesgo operativo')),
                ('is_server', models.BooleanField(default=False, verbose_name='Es servidor')),
                ('is_network_device', models.BooleanField(default=False, verbose_name='Es dispositivo de red')),
                ('last_scan_date', models.DateField(blank=True, null=True, verbose_name='Último escaneo de seguridad')),
                ('antivirus', models.CharField(blank=True, max_length=100, verbose_name='Antivirus instalado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas TI')),
            ],
            options={
                'verbose_name': 'Perfil TI del activo',
                'verbose_name_plural': 'Perfiles TI de activos',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('software_name', models.CharField(max_length=150, verbose_name='Nombre del software')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Versión')),
                ('license_key', models.CharField(blank=True, max_length=255, verbose_name='Clave de licencia')),
                ('license_type', models.CharField(choices=[('PERPETUA', 'Licencia perpetua'), ('SUSCRIPCION', 'Suscripción anual'), ('OEM', 'OEM'), ('OPEN_SOURCE', 'Código abierto'), ('VOLUMEN', 'Licencia por volumen')], max_length=15, verbose_name='Tipo de licencia')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Número de licencias')),
                ('used_seats', models.PositiveIntegerField(default=0, verbose_name='Licencias en uso')),
                ('vendor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo ($)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('assets', models.ManyToManyField(blank=True, related_name='licenses', to='assets.asset', verbose_name='Activos asignados')),
            ],
            options={
                'verbose_name': 'Licencia de software',
                'verbose_name_plural': 'Licencias de software',
                'ordering': ['software_name'],
            },
        ),
    ]
