# Generated by Django 4.2.13 on 2026-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('GARANTIA', 'Por garantía'), ('EMERGENCIA', 'Emergencia')], max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido (sin realizar)')], default='PROGRAMADO', max_length=15, verbose_name='Estado')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('technician', models.CharField(blank=True, max_length=150, verbose_name='Técnico responsable')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Empresa / Proveedor')),
                ('work_order', models.CharField(blank=True, max_length=50, verbose_name='N° Orden de trabajo')),
                ('description', models.TextField(verbose_name='Descripción del trabajo realizado')),
                ('findings', models.TextField(blank=True, verbose_name='Hallazgos')),
                ('parts_replaced', models.JSONField(blank=True, null=True, verbose_name='Partes/piezas reemplazadas')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo ($)')),
                ('downtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Horas fuera de servicio')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Registro de mantenimiento',
                'verbose_name_plural': 'Registros de mantenimiento',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
