# Generated by Django 4.2.13 on 2026-04-24 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False  # MySQL: evitar bloqueos con ALTER TABLE y FK constraints

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='technician',
            field=models.CharField(blank=True, max_length=150, verbose_name='Técnico responsable (nombre)'),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('is_external', models.BooleanField(default=False, verbose_name='Es técnico externo')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa / Proveedor')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='Especialidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema (si es interno)')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido (sin realizar)')], max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones del cambio')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del cambio')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='maintenance.maintenancerecord', verbose_name='Registro de mantenimiento')),
            ],
            options={
                'verbose_name': 'Log de estado de mantenimiento',
                'verbose_name_plural': 'Logs de estado de mantenimiento',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='maintenance.technician', verbose_name='Técnico (catálogo)'),
        ),
    ]
