# Generated by Django 4.2.13 on 2026-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_feature_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('ESPERA_REPUESTOS', 'En espera de repuestos'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido (sin realizar)')], default='PROGRAMADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='maintenancestatuslog',
            name='status',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('ESPERA_REPUESTOS', 'En espera de repuestos'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido (sin realizar)')], max_length=20, verbose_name='Estado'),
        ),
    ]
